#- id: '1498759400476'
#  alias: Julgransbelysning Off
#  trigger:
#  - at: '22:30:00'
#    platform: time
#  action:
#  - entity_id: switch.fibaro_wall_plug_1_switch
#    service: homeassistant.turn_off
#- id: '1498759400479'
#  alias: Julgransbelysning On
#  trigger:
#  - at: 07:35:00
#    platform: time
#  action:
#  - entity_id: switch.fibaro_wall_plug_1_switch
#    service: homeassistant.turn_on

    
#- id: '1498757400476'
#  alias: Barnens laddare På
#  trigger:
#  - at: '18:00:00'
#    platform: time
#  action:
#  - entity_id: switch.fibaro_wall_plug_1_switch
#    service: homeassistant.turn_on
    
#- id: '1498757400676'
#  alias: Barnens laddare Av
#  trigger:
#  - at: '22:00:00'
#    platform: time
#  action:
#  - entity_id: switch.fibaro_wall_plug_1_switch
#    service: homeassistant.turn_off

    
#- id: '1498757400576'
#  alias: Magic Mirror On
#  trigger:
#  - at: '06:00:00'
#    platform: time
#  action:
#  - entity_id: switch.magic_mirror_monitor
#    service: homeassistant.turn_on
    
#- id: '1498777400676'
#  alias: Magic Mirror Off
#  trigger:
#  - at: '23:00:00'
#    platform: time
#  action:
#  - entity_id: switch.magic_mirror_monitor
#    service: homeassistant.turn_off
    
        
    

    

#- alias: Turn bathroom lights on if motion detected
#  trigger:
#    platform: state
#    entity_id: sensor.multisensor_badrum_burglar
#    from: '0'
#    to: '8'
#  condition:
#    condition: state
#    entity_id: sensor.media_room
#    state: 'PowerOff'
#  action:
#    service: switch.turn_on
#    entity_id: switch.dimmer_stora_badrummet_switch
#    data:
#      brightness: 80


#- alias: Turn bathroom lights off if no motion detected
#  trigger:
#    platform: state
#    entity_id: sensor.multisensor_badrum_burglar
#    from: '8'
#    to: '0'
#  action:
#    service: switch.turn_off
#    entity_id: switch.dimmer_stora_badrummet_switch

    
 
#- action:
#  - entity_id: switch.dimmer_stora_badrummet_switch
#    service: switch.turn_on
# alias: Turn bathroom lights on if motion detected on night
#  condition:
#  - after: sunset
#   condition: sun
#  id: '1515672811344'
#  trigger:
#  - entity_id: sensor.aeotec_multisensor_6_badrum_burglar
#    from: '0'
#    platform: state
#    to: '8'


# Denna konstiga regel verkar låsa dörren om larmet går på.
#- action:
#  - entity_id: switch.magic_mirror_monitor
#    service: switch.turn_off
#  - entity_id: lock.ytterdorr
#    service: lock.lock
#    data:
#      code: 193906
#  alias: Alarmet
#  condition: []
#  id: '1515767364158'
#  trigger:
#  - entity_id: input_boolean.larm
#    from: 'off'
#    platform: state
#    to: 'on'

    
#- alias: Turn Mirrorscreen off if no motion detected
#  trigger:
#    platform: state
#    entity_id: sensor.multisensor_lekdel_burglar
#    from: '8'
#    to: '0'
#      minutes: 30
#  action:
#    service: switch.turn_off
#    entity_id: switch.magic_mirror_monitor
#
    
#- alias: Turn Mirrorscreen on if motion detected
#  trigger:
#    platform: state
#    entity_id: sensor.multisensor_lekdel_burglar
#    from: '0'
#    to: '8'
#  action:
#    service: switch.turn_on
#    entity_id: switch.magic_mirror_monitor
#    
#- alias: Turn Mirrorscreen off if no motion detected
#  trigger:
#    platform: state
#    entity_id: sensor.multisensor_lekdel_burglar
#    from: '8'
#    to: '0'
#    for:
#      minutes: 2
#  action:
#    service: switch.turn_off
#    entity_id: switch.magic_mirror_monitor


    
